### PR TITLE
Create Attachments from Buffers

### LINKED ISSUE #1: Allow creation of attachments outside the context of a file sent via HTTP request
## Why this feature is required (specific use-cases will be appreciated)?
Many apps manage files that come from other sources than an HTTP request, for example an app might create invoices in a scheduled task, or process videos in a background job. And currently ```Attachment.fromFile()``` requires a MultipartFileContract file to be passed in, which currently can only be obtained by using ```request.file or request.files``` which of course are available only in HTTP requests, if we could pass a NodeJS Buffer, or create an object compatible with MultipartFileContract from a Buffer, this would be solved

## Have you tried any other work arounds?
Yes, currently it's possible to do this by creating the file manually using Adonis Drive and creating the attachment using ```Attachment.fromDbResponse``` with a fake db response object.

## Are you willing to work on it with little guidance?
Yes

### PR DESCRIPTION
**Pull request by ndianabasi**
## Proposed changes

There is a special and important use case for creating attachments outside the HTTP request lifecyle. Imagine having the ability to attach a PDF invoice to an `Invoice` model after the PDF file is generated by an external service via a message queue. Or having the ability to attach an avatar to a `User` model after it is optimised by an external service or after it is fetched from an external source outside of the HTTP request lifecycle.

This PR implements the use case described above by providing the `Attachment.fromBuffer` static method for creating an `Attachment` instance from `Buffer`s.

## Types of changes

What types of changes does your code introduce?

_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [CONTRIBUTING](https://github.com/adonisjs/attachment-lite/blob/master/CONTRIBUTING.md) doc
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] I have added necessary documentation (if appropriate)

## Related Issues:

- Fixes #1

### CODE REVIEW

**Comment by ndianabasi** [comment]
I noticed non-structural changes to files I did not modify. I think this might be caused by the recent change from Windows to Linux OS. But it appears not to affect other repos I access.

I don't know if this will affect the acceptance of this PR. :(

**Comment by thetutlage** [comment]
Yeah, there are too many changes. I recommend simply ignoring the files which got formatting changes coz of a different OS

**Comment by ndianabasi** [comment]
Okay. I will re-issue the PR. Thank you.

**Comment by RomainLanz** [comment]
@thetutlage I believe we should add a `.gitattributes` file that forces EOL to `LF`.

The `.editorconfig` file should do it, but it depends on what editor you are using, whereas `git` is installed in all machines if you want to create clone/PR a project.

**Comment by thetutlage** [comment]
Closing since the change is not something I want to add right now. Also had a word with @ndianabasi and he can accomplish the task without this change

**Comment by maxifuchs** [comment]
Hey @thetutlage and @ndianabasi,
would you mind sharing your solution/how you overcame the issue?
Since I would like to generate a ZIP File on the server and then also save the Buffer into an Attachment, which unfortunately is currently not supported

**Comment by ndianabasi** [comment]
Hi @maxifuchs. Have a look at this PR: https://github.com/ndianabasi/adonis-responsive-attachment/pull/1

**Comment by madebylydia** [comment]
Even if this is a old PR, I'd like if @thetutlage could reconsider adding this functionality.

The actual problem of attachment-lite that I personally encountered is that I can only use it in a HTTP request, unallowing me to create a Attachment object without the HTTP server running. At least, I've not seen a way to do so.

As for now, `.fromDatabase` method needs a response from the database, assuming the resource exist, and `.fromFile` requires a object implementing `MultipartContract`, which is usually only in a HTTP request.

This, as I'm saying, would allow developers to create an Attachment object more easily and in an ergonomic way.

If you are agreeing with me, I can open a new issue to help you keep track or maybe try to take again the work of @ndianabasi if he agrees, or maybe he wpuld open a new PR himself. :)

**Comment by myckhel** [comment]
I managed to upload the files manually and still took advantage of the attachment-lite

### Save the unitArray/buffer as a file
```ts
await fs.writeFile(tmpFilename, buffer)
```

### Read the temp file as Buffer
```ts
const tmpFileBuffer = await fs.readFile(tmpFilename)
```
### Use Attachment light to save the file in the folder
```ts
const folderName = 'signed-docs'
const filePath = `${folderName}/${name}.pdf`

await Attachment.getDrive().put(filePath, tmpFileBuffer)
```

### Save the model and file prop to db with raw query
```ts
await Database.table('signed_docs').insert({
    doc_id: doc.id,
    signer_id: signer.id,
    file: {
      name: filePath,
      extname: 'pdf',
      size: saved.length,
      mimeType: 'application/pdf',
    },
  })
```
### Delete the temporary file when done
```ts
await fs.unlink(tmpFilename)
```

### All Codes

```ts
await fs.writeFile(tmpFilename, fileBuffer)

const tmpFileBuffer = await fs.readFile(tmpFilename)

const folderName = 'signed-docs'
const filePath = `${folderName}/${name}.pdf`

await Attachment.getDrive().put(filePath, tmpFileBuffer)

await Database.table('signed_docs').insert({
    doc_id: doc.id,
    signer_id: signer.id,
    file: {
      name: filePath,
      extname: 'pdf',
      size: saved.length,
      mimeType: 'application/pdf',
    },
  })

await fs.unlink(tmpFilename)
```

**Comment by krthr** [comment]
Is there any plan to implement this in the future?

**Comment by filipebraida** [comment]
I used this code:

```typescript
  import { cuid } from '@poppinss/utils/build/helpers'
  import detect from 'detect-file-type'

  type BufferProperty = { ext: string; mime: string }
  let bufferProperty: BufferProperty | undefined

  detect.fromBuffer(buffer, function (err: Error | string, result: BufferProperty) {
    if (err) {
      throw new Error(err instanceof Error ? err.message : err)
    }
    if (!result) {
      throw new Error('Please provide a valid file buffer')
    }
    bufferProperty = result
  })

  const { mime, ext } = bufferProperty!

  const name = `${cuid()}.${ext}`

  const attributes = {
    extname: ext,
    mimeType: mime,
    size: buffer.length,
    name: name,
  }

  await Attachment.getDrive().put(name, buffer)

  const file = Attachment.fromDbResponse(JSON.stringify(attributes)))

  // create the object using file var
```
I used this package as a reference
https://github.com/ndianabasi/adonis-responsive-attachment/

**Pull request closed without merging**
