### PR TITLE
feat: add multiple option to attachment decorator

### PR DESCRIPTION
**Pull request by guoyunhe**
## Proposed changes

Sometimes we need to attach multiple files to a model, e.g. a job application may contain CV, cover letter, portfolio, copy of degree certificates, etc.

This PR add an `multiple` option to the decorator. Like this:

```ts
class User extends BaseModel {
  @attachment({ multiple: true })
  public photos: AttachmentContract[]
}
```

## Types of changes

What types of changes does your code introduce?

_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [CONTRIBUTING](https://github.com/adonisjs/attachment-lite/blob/master/.github/CONTRIBUTING.md) doc
- [ ] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] I have added necessary documentation (if appropriate)

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by guoyunhe** [comment]
I am not able to run all the unit tests. Some tests failed with no details. The other tests don't even run...

图片

**Comment by ndianabasi** [comment]
Hi @guoyunhe.

Thanks for your PR. Did you discuss with Virk if he would like this feature adopted before beginning the PR?

**Comment by guoyunhe** [comment]
@ndianabasi No.

**Comment by justDare** [comment]
This is SO damn useful, I hope you get permission + passing tests to get this added.

**Comment by thetutlage** [comment]
I think multiple attachments should be represented as multiple rows in the database. For example: I will rather have `user_photos` table and then give user the ability to delete or update each photo as a database row vs storing all photos in a single array.

So, for now I will skip this PR to keep the codebase simple :)

**Pull request closed without merging**
